### ISSUE TITLE
Mid-run update causing geometry to disappear

### ISSUE THREAD

**Issue by ericvmueller** [firemodels/smv#1558]
Running the case posted in https://github.com/firemodels/fds/issues/11781 I notice that pressing 'u' to update boundary output during the run causes the geometry to randomly disappear in some or all of the meshes (the canyon should appear in both of the lower meshes).

![image](https://user-images.githubusercontent.com/13366803/235239973-d9d2be21-3943-47a2-8984-d319d79c7937.png)

**Comment by gforney** [comment]
thanks.  I'll take a look.

**Comment by gforney** [comment]
should be fixed in smokeview posted here
https://github.com/firemodels/test_bundles/releases/tag/SMOKEVIEW_TEST
and also after updating smv repo and building smokeview

**Comment by ericvmueller** [comment]
Hmm I rebuilt smokeview but still get some strange vanishing behavior if I update enough during a run. 
I can send you the location of the case if you want to test it.

![image](https://user-images.githubusercontent.com/13366803/235703935-038593c5-4fc1-4f3f-b496-bcf358c538c8.png)

**Comment by gforney** [comment]
thought I found the problem.  I'm seeing same thing - didn't hit 'u' enough times yesterday.  I'll keep looking

**Comment by gforney** [comment]
try it now.  either build smokeview after updating your smv repo or download a test smokeview from here
https://github.com/firemodels/test_bundles/releases/tag/SMOKEVIEW_TEST

**Comment by ericvmueller** [comment]
Yup, looks to be working fine now. Thanks!

**Comment by gforney** [comment]
a similar problem could occur with other file types.  let me know if you see anomalies when you press 'u' when slice, particle, 3d smoke files etc are loaded
